### ISSUE TITLE
Implement 3DViewer()

### ISSUE THREAD

**Issue by arpastrana** [arpastrana/apc524_directional_clustering#10]
A viewer that displays multiple meshes and multiple vector fields simultaneously in 3d space

**Comment by isabelmdo** [comment]
Progress update:
3D viewer displays clustered output images on a given mesh and the directions of the lines of a given vector field. 
The output is in HTML with an interactive viewer. 

Next steps: 
Modularize the currently linear code.
Embed interactive viewer in Sphinx documentation.

**Comment by isabelmdo** [comment]
Working code with example 01_directional_clustering.py 

Next:
Add tests prior to pull request
Embed interactive viewer in Sphinx documentation.

**Comment by arpastrana** [comment]
Closed after #29.
