### ISSUE TITLE
Broken draw_vector_field_array 

### ISSUE THREAD

**Issue by isabelmdo** [arpastrana/apc524_directional_clustering#23]
I believe one of the latest commits may have broken the vector field array. 
I'm looking into it, and hope to find a solution, but please let me know if you have a hint on where it may have gone wrong! 
Thanks :)

When I set `draw_vector_fields = True` his error happens:

```
Traceback (most recent call last):
  File "01_directional_clustering.py", line 285, in <module>
    plotter.draw_vector_field_array(va, (50, 50, 50), True, 0.07, 0.5)
  File "c:\users\(...)\apc524_directional_clustering\src\directional_clustering\plotters\cluster_plotter.py", line 39, in draw_vector_field_array
    rows, cols = field.shape
AttributeError: 'VectorField' object has no attribute 'shape'
```

**Comment by arpastrana** [comment]
I think this is because `VectorField` used to be a `np.array`, but now it is its own class. A quick hack to replace line `285` would be:
```python
rows = len(list(field.vectors())  # actually, this suggests implementing VectorField.number_of_vectors() as a shorthand!
cols = field.dimensionality()
```
Though I'm not sure if more things are broken down the road!

**Comment by isabelmdo** [comment]
I don't think that did the trick =/ 
I noticed something else as well:
If I only run script 01_directional_fields.py as is (with `draw_vector_fields = False`) there are more colors being plotted - one for each portion of the mesh. So I would assume that the direction is not 'calibrated' anymore.

**Comment by arpastrana** [comment]
Would you mind posting a code snippet and a screenshot of what you are seeing? 🍔

**Comment by isabelmdo** [comment]
After reviewing the latest changes in 01_directional_clustering.py I found the missing lines and reincluded them in the branch plotters. As far as I know, it only affects plotters, and it shouldn't create any new conflicts.
