### ISSUE TITLE
An error coming up when trying to get attributes of a face using mesh.face_attribute(s)

### ISSUE THREAD

**Issue by hhhhuiyuan** [arpastrana/apc524_directional_clustering#24]
**Describe the bug**
I was trying to get attributes of a face using `mesh.face_attribute(fkey)` or `mesh.face_attributes(fkey)`, but neither way worked.
`mesh.face_attribute(fkey)`: An error came up `missing 1 required positional argument: 'name'`
`mesh.face_attributes(fkey)`: returned an empty dictionary

**To Reproduce**
My code is:
```
import os
from compas.datastructures import Mesh
from directional_clustering import JSON

name_in = "perimeter_supported_slab.json"
JSON_IN = os.path.abspath(os.path.join(JSON, name_in))

mesh = Mesh.from_json(JSON_IN) 
fkey = mesh.get_any_face()
attr = mesh.face_attributes(fkey)
print(len(attr))
```

**Comment by arpastrana** [comment]
I have an idea about this. As we discussed, `mesh.face_attributes(fkey)` will return a very weird `FaceAttributeView` object which stores a copy of the attributes of a face in a dictionary `{attribute_name: attribute_value}` whose keys can be iterated over via `FaceAttributeView.keys()` (this is a generator), and printed using `list(FaceAttributeView.keys())` (parsing a generator into a list). 

Internally, however, `FaceAttributeView` makes a distinction between **default** and **custom** face attributes. Oddly enough, `FaceAttributeView` will only return by default the keys of the **default** attributes of the faces of a mesh, which is nothing more than a default dictionary defined at a mesh instantiation which some preset fallback values. In our case, the vector fields are all **custom** attributes that were added to a mesh on the fly, post-instantiation, and there are no **default** attributes. Therefore, when calling something like `list(FaceAttributeView.keys())`, the output will be an empty list.

The solution would be to modify one of the attributes of `FaceAttributeView` to only the **custom** attributes with one of the following snippets:

Option 1
```python
attr_view = mesh.face_attributes(fkey)
print(list(attr_view.keys()))  # outputs an empty list
attr_view.custom_only = True
print(list(attr_view.keys()))  # outputs a list with all the "custom" attribute names
```

Option 2
```python
attr_view = mesh.face_attributes(fkey)
print(list(attr_view.attr.keys()))  # outputs a list with all the "custom" attribute names
```

In both cases, if there were any **default** face attributes, they will probably not show up.

**Comment by hhhhuiyuan** [comment]
Very helpful! Both two options works! 
I'll join both the **default** and **custom** attribute lists and search supported vector_field attributes from that joined list, in case that some vector_field is under a **default** attribute.

**Comment by isabelmdo** [comment]
This explanation makes a lot of sense. It wasn't clear to me from the last discussion we had on getting face attributes why one method was working and the other wasn't. 👍

**Comment by arpastrana** [comment]
Closing this as per f9ee20a8516635e779094d9ca4c318d89b9fbedc.
