### ISSUE TITLE
Branch: plotters

### ISSUE THREAD

**Issue by isabelmdo** [arpastrana/apc524_directional_clustering#25]
# Opinion/trial Request
I've added the new plotter to the *plotters* branch and it would be great if someone could see it (:eyes: @arpastrana) before I continue making progress. My next steps are to add tests and make a PR before continuing to expand the plotting options, or changing it into a class rather than functions.

## Details

1. **Install plotly.py with:**
    * pip
`$ pip install plotly==4.13.0`
    * conda
`$ conda install -c plotly plotly=4.13.0`

2. **See if script 01_directional_clustering.py works**
Simply run that script to see if a new tab opens in your browser to show the interactive graph. You can change the plotter flags at the top of the script - there is an added option to draw mesh edges or not.

3. **Overleaf: Plotters**
For curiosity: there is a file inside our Overleaf report folder with a detailed description of why I chose plotly.py package, along with the issues and solutions I found. I made that mainly to organize my own work process, but it may be useful to others since I had to do quite some digging in forums and documentation to find the solutions I was looking for.

**Comment by arpastrana** [comment]
@isabelmdo Just had a look. It works on my machine! 🙌🏽  Invoking `go.Figure()`is hillarious!

Development-wise, I would suggest listing `plotly` as a dependency in `requirements.txt`. This should install this package whenever anyone makes a fresh install of `directional_clustering`.

Structure-wise, the suggestion would be to have all the `plotly` imports internal to `directional_clustering.plotters` and not in the `driver` code (01.directional_clustering.py). Ideally:
- `ply_draw_trimesh()` would be called as a one-liner (just like `ply_draw_vector_field_array()`) and it should take care of all the formatting internally (making dictionaries or lists)
- These methods should take in `MehsPlus` and `VectorField` objects in their signature too.

Also I find a bit confusing to `ply_plotter = go.Figure()` instantiated in the driver code, and then passed in as an argument to `pp`. Is this avoidable?

One alternative is to create an e.g. `MeshPlyPlotter(mesh)` object that takes care of the `pp` - `go.Figure()` interaction, default colors, etc., with methods: `MeshPlyPlotter.draw_trimesh(*args, **kwargs)`, and `MeshPlyPlotter.draw_vector_field(*args, **kwargs)`.

**Comment by isabelmdo** [comment]
Hi @arpastrana , great! Yep, I thought `go.Figure()` is genius lol

- Development-wise: I'll add a hotfix to add `plotly` to requirements asap.

- Structure-wise: agreed, I have those on my list for the refactoring phase now. I made simple/sub-ideal functions just to get it working. :) 

All sounds good. Thanks for testing, looking at the code, and adding these suggestions!
