### ISSUE TITLE
Sphinx - template

### ISSUE THREAD

**Issue by isabelmdo** [arpastrana/apc524_directional_clustering#30]
**To Reproduce**
`invoke docs`

**The error I get is**
compas_template is not installed.

**The solution I found**
... was to `pip install sphinx-compas-theme` .

**Question**
Should we add it to `requirements.txt` ?

**Comment by arpastrana** [comment]
@isabelmdo Actually, `sphinx-compas-theme` is listed in `requirements-dev.txt`(the stuff developers like us need ;) ), so it is not necessary to list in in `requirements.txt` (the dependencies for general users). This is listed in the `CONTRIBUTING.md` file. I forgot to remind us of that little detail -- sorry! However, I agree that it should be good to add a note under the "contributing section" of `README.md` saying something like: "make sure to update your dependencies as said in the contribution guide", etc.
