### ISSUE TITLE
Sphinx - matplotlib

### ISSUE THREAD

**Issue by isabelmdo** [arpastrana/apc524_directional_clustering#31]
**To Reproduce**
`invoke docs`

**The error I get is**
 ```
app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'alt'
```
It is very similar to the one described here: https://github.com/sphinx-doc/sphinx/issues/7659 
One of the comments describes exactly the error I copied above.

**The solution I found**
... was to downgrade sphinx to 2.4, because, for some reason, I can't upgrade matplotlib to anything above 3.0.3. Does anyone have a clue why this is happening?

**Bonus problem!**
When `invoke docs` finally works, I can't find any of our documentation in the HTML, only the headers.
For this issue, I believe it is simply because I haven't spent much time yet figuring out how sphinx works. But I thought it would be good to include this part here anyways in case someone already knows what's up with it.

**Additional context**
I'm running Windows 10, with windows cmd prompt, inside conda env. *clusters*.

**Comment by arpastrana** [comment]
@isabelmdo Did you get this error after you tried something in particular (e.g. embedding html into sphinx) or was it after running plain and simple `invoke docs` for the first time? 🙂

**Comment by isabelmdo** [comment]
@arpastrana 
Just plain and simple `invoke docs` for the first time.

I did the tutorial linked in our class notes and I had the same issue with the docs not showing up, so it could be something related to Windows that I'm still not aware of. I'll look into that later today!

**Comment by arpastrana** [comment]
@isabelmdo ran plan `invoke docs` for the first time on my side without issues (mac, clusters environment). This can be misleading though because I've ran this command multiple times for other projects (in other conda environments, tho). But AFAIR, I didn't see an error like this showing up.

**Comment by isabelmdo** [comment]
Just a comment to follow up on what happened here: docs are showing up fine in HTML, but matplotlib-sphinx error persists. I changed the version of Sphinx in `requirements-dev.txt`
